import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { Product } from '../types/interfaces';

// Define the interface for the state
interface ProductState {
  products:Product[]
}

// Define the initial state
const initialState: ProductState = {
  products: [],
};

// Create a slice
const ProductSlice2 = createSlice({
  name: 'products',
  initialState,
  reducers: {
    setProducts:(state,action:PayloadAction<Product[]>)=>{
         state.products = action.payload;
    }
  },
});

// Export the actions generated by the slice
export const { setProducts } = ProductSlice2.actions;

// Export the reducer
export default ProductSlice2.reducer;
